### ISSUE TITLE
Visualization software

### ISSUE THREAD

**Issue by wusuoweima** [ChrisWu1997/Multimodal-Shape-Completion#2]
吴同学你好，我刚刚看了你在极市上论文的讲解，工作很棒兼得也很清晰。我对你实验结果的可视化比较感兴趣， 你使用的可视化软件和网络训练过程中的可视化方法可以分享下吗？

**Comment by ChrisWu1997** [comment]
谢谢关注我们的工作。点云的图片是先通过脚本将每个点转成球状的mesh，再通过keyshot软件渲染的。 网络训练过程就只是用tensorboard可视化的。

**Comment by CRISZJ** [comment]
> 吴同学你好，我刚刚看了你在极市上论文的讲解，工作很棒兼得也很清晰。我对你实验结果的可视化比较感兴趣， 你使用的可视化软件和网络训练过程中的可视化方法可以分享下吗？
您好，我对这篇工作也非常感兴趣，您能附上极市的讲解链接地址吗

**Comment by ChrisWu1997** [comment]
这个视频里面应该有：https://www.bilibili.com/video/BV1JZ4y1K7wP

**Comment by CRISZJ** [comment]
> 这个视频里面应该有：https://www.bilibili.com/video/BV1JZ4y1K7wP

非常感谢，您的工作做的非常好，讲解也很清楚
