### ISSUE TITLE
关于partial shape输入pointAE时点的个数的疑惑

### ISSUE THREAD

**Issue by shilei-ustcer** [ChrisWu1997/Multimodal-Shape-Completion#4]
吴同学，你好，很棒的工作。

我有一个小问题，在partial shape的点feed到pointAE时，我看代码实现中，parital shape点云的个数是complete shape的一半，1024对应2048，但是我看在paper中，“ we duplicate the partial point set of K points to align with the number of complete point set before feed it to AE”， 是指partial shape中的点的个数也要2048吗？

一个小疑惑，希望得到你的解答。

**Comment by ChrisWu1997** [comment]
您好！这个应该是写文章时的一个疏忽，应当按照代码里的来，是一半。不过这个数值的影响应该不大，1024和2048都是可以的。
