### ISSUE TITLE
3D-EPN Download Link

### ISSUE THREAD

**Issue by orrkrup** [ChrisWu1997/Multimodal-Shape-Completion#7]
Hi, 
I'm trying to download the 3D-EPN dataset, but the PKU Disk link has expired. Is it possible to renew it, or point to a different link?

Thanks again for sharing your code and the data!

**Comment by ChrisWu1997** [comment]
Hi @orrkrup, I just update the link. Try this: https://disk.pku.edu.cn:443/link/10DB3F94D4578FD9D4ADF026561E9F4C.

**Comment by tsa87** [comment]
Hi @ChrisWu1997, could you please update the PKU Disk link again? Thank you!
